// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAw1xHAK_7cToYarRz84b77kOaItA7Lnc',
    appId: '1:105840336181:web:0bd02efb19168a8387c07c',
    messagingSenderId: '105840336181',
    projectId: 'dream-96b28',
    authDomain: 'dream-96b28.firebaseapp.com',
    storageBucket: 'dream-96b28.firebasestorage.app',
    measurementId: 'G-XKVVMRCDMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFHKiN8oEMM-ZTHHs379MN06dWFOapiDg',
    appId: '1:105840336181:android:53b28b858afd2f6e87c07c',
    messagingSenderId: '105840336181',
    projectId: 'dream-96b28',
    storageBucket: 'dream-96b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4AM6_aQYX75pIHgHBngV-9O-KSgXtz4',
    appId: '1:105840336181:ios:db7803029b86189c87c07c',
    messagingSenderId: '105840336181',
    projectId: 'dream-96b28',
    storageBucket: 'dream-96b28.firebasestorage.app',
    iosBundleId: 'top.neuronx.dream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC4AM6_aQYX75pIHgHBngV-9O-KSgXtz4',
    appId: '1:105840336181:ios:db7803029b86189c87c07c',
    messagingSenderId: '105840336181',
    projectId: 'dream-96b28',
    storageBucket: 'dream-96b28.firebasestorage.app',
    iosBundleId: 'top.neuronx.dream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAw1xHAK_7cToYarRz84b77kOaItA7Lnc',
    appId: '1:105840336181:web:0efc0c027d8fb0e487c07c',
    messagingSenderId: '105840336181',
    projectId: 'dream-96b28',
    authDomain: 'dream-96b28.firebaseapp.com',
    storageBucket: 'dream-96b28.firebasestorage.app',
    measurementId: 'G-9R0H90EZJ7',
  );
}
